### ISSUE TITLE
DNS failures on collectors

### ISSUE THREAD

**Issue by nopzor1200** [raintank/raintank-collector#18]
The collectors seem to be reporting false errors on DNS.

@woodsaj  said "not sure what the issue is, but looks like bug with the collector.   I ran a tcpdump on sin1.sg collector and an error was raised even though a valid response came back from the nameserver"

This problem can be seen across all endpoints in prod

**Comment by woodsaj** [comment]
This looks to be a bug in the third party native-dns library.

tcpdump showing request and valid response:

```
05:16:59.286982 IP (tos 0x0, ttl 64, id 56046, offset 0, flags [DF], proto UDP (17), length 54)
    128.199.222.104.53571 > 204.79.197.1.53: [bad udp cksum 0xf0b4 -> 0x48e9!] 20096+ A? bing.com. (26)
05:16:59.288727 IP (tos 0x0, ttl 123, id 25267, offset 0, flags [none], proto UDP (17), length 70)
    204.79.197.1.53 > 128.199.222.104.53571: [udp sum ok] 20096*- q: A? bing.com. 1/0/0 bing.com. [1h] A 204.79.197.200 (42)
```

But for somereason, the native-dns query is throwing a timeout.

```
[2015-08-03 05:16:59.283] [INFO] PID:29157 - 1438593419282: count: 1 nsservers.len: 4
[2015-08-03 05:16:59.284] [INFO] PID:29157 - 1438593419282: next server to try is:  204.79.197.1
[2015-08-03 05:16:59.284] [INFO] PID:29157 - 1438593419282: performing lookup against:  204.79.197.1
[2015-08-03 05:16:59.285] [INFO] PID:29157 - 1438593419282: nsserver 204.79.197.1 resolved to 204.79.197.1
[2015-08-03 05:17:01.287] [INFO] PID:29157 - 1438593419282: timeout while querying 204.79.197.1 on udp:53
```

The timeout is set to 2seconds. which is reached even though the response packet arrived in less then 2ms.

**Comment by woodsaj** [comment]
spent the day looking into this but unable to isolate the cause. 

I think the best step moving forward is to migrate the DNS check to the GO binary.

**Comment by Dieterbe** [comment]
is it consistent? i wonder if perhaps the udp response doesn't make it into the go runtime.
perhaps the udp buffer is overflowing, which would cause the kernel to drop udp packets. i've seen this problem a lot with statsd. not sure if it should show up in tcpdump then though

**Comment by woodsaj** [comment]
Good suggestion Dieter.

The raintank-collector is consistently, intermittently failing to receive the DNS responses.  

When running a separate test application that uses the same native-dns library at the same time on the same host, there are no dropped dns responses.  The test app was even running with some artificial load to put pressure on the NodeJS eventloop.

The netstat statistics dont indicate that buffers are overflowing, also buffers are per socket and therefore per dns lookup which has a very small response payload that would fit in the buffer.

**Comment by Dieterbe** [comment]
![shrug](https://cloud.githubusercontent.com/assets/20774/9041146/bddaac3e-3a06-11e5-92b5-de26c5a61143.jpg)

**Comment by woodsaj** [comment]
I should also mention, that the other checks (http, https, ping) also need to lookup hostnames but use the standard DNS library (we cant use it for the dns check as it does not allow use to craft our own query). When changing these checks to use the native-dns library, they also start breaking.

**Comment by nopzor1200** [comment]
So I have no idea what the actual issue is but this problem only started on the evening of July 28 it seems.

After that point in time, about ~10% of DNS report errors across many (all?) endpoints. Before that, it was just very sparse and intermittent DNS errors.

Find out what changed and solve this problem?

**Comment by nopzor1200** [comment]
@woodsaj

**Comment by woodsaj** [comment]
made good progress on adding the DNS checking to the Go binary.  Refactored the go binary and moved it to  https://github.com/raintank/raintank-probe

https://github.com/raintank/raintank-collector/pull/20

Just need to do some more testing before deploying to dev-portal

**Comment by woodsaj** [comment]
this has been deployed to production.

**Comment by Dieterbe** [comment]
@woodsaj yesterday i read something in https://tip.golang.org/doc/go1.5 which will probably be quite useful to us:

> The DNS resolver in the net package has almost always used cgo to access the system interface. A change in Go 1.5 means that on most Unix systems DNS resolution will no longer require cgo, which simplifies execution on those platforms. Now, if the system's networking configuration permits, the native Go resolver will suffice. The important effect of this change is that each DNS resolution occupies a goroutine rather than a thread, so a program with multiple outstanding DNS requests will consume fewer operating system resources. 

let's hope the resolver is actually good, too ;)

**Comment by woodsaj** [comment]
it will help with performance of other checks, as each check needs to resolve hostnames, but not for the DNS check. The reason being that we need to use a full DNS client library and not just a resolver.  We currently use  github.com/miekg/dns
