### ISSUE TITLE
limit timeout value to 80% of check interval

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-collector#34]
seeing lots of dropped metrics with new metric-tank TSDB as it requires metrics to be sent in order.

Metrics that have a check interval of 10seconds and a timeout of 10seconds are sometime arriving out of order.

By restricting timeouts to 80% of the check interval, we can be sure that there will be enough of a delay between the check failing and the next check running.

**Comment by Dieterbe** [comment]
if interval is 60s, a timeout of 48s still seems needlessly long though.
so maybe timeout should be like `lower(0.8*interval, 15)` ?
