### ISSUE TITLE
check execution time can creep forward if server under high load

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-collector#6]
Because we are currently using setInterval() to continually run checks we can't guarantee that checks will always run when we want them to.

We need to move away from setInterval and instead continually call setTimeout() adjusting the wait period as needed.

**Comment by Dieterbe** [comment]
@woodsaj i just wanna make sure, this not only fixes the schedule times, it also garantees correctness of the timestamps of the points, right? (meaning all emitted points fulfill timestamp % freq == offset)

**Comment by woodsaj** [comment]
@Dieterbe yes.  All metrics sent will always have the timestamp set correctly.
